apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-server-config
data:
  my_res.json: |
    [
      {
        "name": "resource1",
        "value": "Valore Alpha"
      },
      {
        "name": "resource2",
        "value": "Valore Beta"
      }
    ]


